pak/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2007 Ekrem SEREN
# Licensed under the terms of CC Attribution-NonCommercial-ShareAlike 3.0 (CC ByNcSa3)
# See: http://creativecommons.org/licenses/by-nc-sa/3.0/
# 09-12-2007
#
# Coded with Wing IDE v3 with pleasure.
# http://wingware.com/

from django.conf.urls.defaults import *
from porsuk.pak.views import *
from porsuk.pak.models import *
from porsuk.settings import PACKAGES_PER_PAGE
from django.shortcuts import get_object_or_404

urlpatterns = patterns('',
    (r'packages/$', "django.views.generic.simple.redirect_to", {"url": "/pisi/packages/order-by/name"}),
    (r'packages/order-by/(?P<orderby>.*)$', packages),
    (r'package/(?P<id>.*)$', package),
    (r'sources/$', "django.views.generic.simple.redirect_to", {"url": "/pisi/sources/order-by/name"}),
    (r'sources/order-by/(?P<orderby>.*)$', sources),
    (r'source/(?P<id>.*)/$', source),
    (r'repositories/$', "django.views.generic.simple.redirect_to", {"url": "/pisi/repositories/order-by/name"}),
    (r'repositories/order-by/(?P<orderby>.*)$', repositories),
    (r'repository/(?P<repo>.*)/(?P<type>.*)$', repository),
    (r'packagers/$',  "django.views.generic.simple.redirect_to", {"url": "/pisi/packagers/order-by/name"}),
    (r'packagers/order-by/(?P<orderby>.*)$', packagers),
    (r'packager/(?P<name>.*)/(?P<type>.*)$', packager_info),
    (r'packager/(?P<name>.*)$', packager),
    (r'updates/$',  "django.views.generic.simple.redirect_to", {"url": "/pisi/updates/order-by/-date"}),
    (r'updates/type/(?P<type>.*)$', updates),
    (r'updates/order-by/(?P<orderby>.*)$', updates),
    (r'update/(?P<id>.*)$', update),
    (r'search/(?P<pattern>.*)$', search),
)

urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2007 Ekrem SEREN
# Licensed under the terms of CC Attribution-NonCommercial-ShareAlike 3.0 (CC ByNcSa3)
# See: http://creativecommons.org/licenses/by-nc-sa/3.0/
#
# Coded with Wing IDE v3 with pleasure.
# http://wingware.com/

from django.conf.urls.defaults import *
from porsuk.pak.views import mainpage
from porsuk.settings import DOCUMENT_ROOT, WEB_URL

#if WEB_URL.split("/")[3:]:
#    k = "/".join(WEB_URL.split("/")[3:]) + "/"
#else:
k = ""

urlpatterns = patterns('',
     (r'^%s$' % k, mainpage),
     (r'^%spisi/' % k, include('porsuk.pak.urls')),
     (r'^%sadmin/' % k, include('django.contrib.admin.urls')),
     (r"^%smedia/(.*)$" % k, "django.views.static.serve", {"document_root": "%s/media" % DOCUMENT_ROOT, "show_indexes": True}), 
     (r'^i18n/', include('django.conf.urls.i18n')),
)

pak/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2007 Ekrem SEREN
# Licensed under the terms of CC Attribution-NonCommercial-ShareAlike 3.0 (CC ByNcSa3)
# See: http://creativecommons.org/licenses/by-nc-sa/3.0/
# 09-12-2007
#
# Coded with Wing IDE v3 with pleasure.
# http://wingware.com/

from django.db import models
from porsuk.settings import WEB_URL, PACKAGE_PREFIX
from django.utils.translation import ugettext as _

class DBDate(models.Model): # Source (Belki Package da)
    # Otomatik olaran nesnenin yaratıldığı zamanı değer olarak alır.
    created = models.DateTimeField(_('DB Creation Date&Time'), auto_now_add=True)
    
    def __unicode__(self):
        return str(self.created)
    
    class Admin:
        pass
    
    class Meta:
        verbose_name = _('Creation Date')
        verbose_name_plural = _('Creation Dates')

class License(models.Model): # Source  
    license = models.CharField(_('License'), max_length=50, unique=True)
    url = models.URLField(_('URL'), blank=True, null=True)

    def __unicode__(self):
        return self.license

    class Admin:
        list_display = ('license', 'url')

    class Meta:
        verbose_name = _("License")
        verbose_name_plural = _("Licenses")

class Summary(models.Model): # Source  
    lang = models.CharField(_("Language"), max_length=2)
    summary = models.CharField(_('Summary'), max_length=600)

    def __unicode__(self):
        return self.lang.upper() + ' ' + self.summary[:50] + "..."

    class Admin:
        list_display = ('lang', 'summary')

    class Meta:
        verbose_name = _("Summary")
        verbose_name_plural = _("Summaries")

class Description(models.Model): # Source  
    lang = models.CharField(_("Language"), max_length=2)
    desc = models.CharField(_('Description'), max_length=1500)

    def __unicode__(self):
        return self.lang.upper() + ': ' + self.desc[:50] + "..."

    class Admin:
        list_display = ('lang', 'desc')

    class Meta:
        verbose_name = _("Description")
        verbose_name_plural = _("Descriptions")

class Patch(models.Model): # Source 
    name = models.CharField(_('Patch'), max_length=100)
    level = models.IntegerField(_('Level'), null=True)

    def __unicode__(self):
        return self.name

    class Admin:
        pass

    class Meta:
        verbose_name = _("Patch")
        verbose_name_plural = _("Patches")

class Repo(models.Model): # Source 
    name = models.CharField(_('Name'), max_length=30, unique=True)
    url = models.URLField(_('URL'))
    def __unicode__(self):
        return self.name

    class Admin:
        list_display = ('name', 'url')

    class Meta:
        verbose_name = _("Repository")
        verbose_name_plural = _("Repositories")

class IsA(models.Model): # Source 
    isa = models.CharField(_('IsA'), max_length=50)

    def __unicode__(self):
        return self.isa

    class Admin:
        pass

    class Meta:
        verbose_name = _("Is A")
        verbose_name_plural = _("Is A's")
        
class LocalName(models.Model):
    lang = models.CharField(_("Language"), max_length=2)
    localname = models.CharField(_('Summary'), max_length=200)
    
    def __unicode__(self):
        return self.localname

    class Admin:
        pass

    class Meta:
        verbose_name = _("Local Name")
        verbose_name_plural = _("Local Names")
        
class Component(models.Model): # Source (Package'a da koyulabilir)
    component = models.CharField(_('Component'), max_length=200)
    localname = models.ManyToManyField(LocalName, verbose_name=_('Local Name'), null=True)
    summary = models.ManyToManyField(Summary, verbose_name=_('Summary'), null=True)
    desc = models.ManyToManyField(Description, verbose_name=_('Description'), null=True)
    
    def __unicode__(self):
        return self.component
    
    def get_component_url(self):
        return "/".join(self.component.split("."))

    class Admin:
        pass

    class Meta:
        verbose_name = _("Component")
        verbose_name_plural = _("Components")


class Dependency(models.Model): # Source&Package
    name = models.CharField(_('Dependency'), max_length=80)
    versionFrom = models.CharField(_('Version From'), max_length=35, blank=True, null=True)
    versionTo = models.CharField(_('Version To'), max_length=35, blank=True, null=True)
    version = models.CharField(_('Version'), max_length=35, blank=True, null=True)
    releaseFrom = models.CharField(_('Release From'), max_length=35, blank=True, null=True)
    releaseTo = models.CharField(_('Release To'), max_length=35, blank=True, null=True)
    release = models.CharField(_('Release'), max_length=35, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "%s/%s/%s" % (WEB_URL, PACKAGE_PREFIX, self.name)

    class Admin:
        list_display = ('name', 'versionFrom')        
    class Meta:
        verbose_name = _("Dependency")
        verbose_name_plural = _("Dependencies")

class Files(models.Model): # Package 
    path = models.CharField(_('Path'), max_length=150)
    fileType = models.CharField(_('fileType'), max_length=50)

    def __unicode__(self):
        return self.fileType + " - " + self.path

    class Admin:
        list_display = ('fileType', 'path')

    class Meta:
        verbose_name = _("File")
        verbose_name_plural = _("Files")

class A_files(models.Model): # Package 
    filename = models.CharField(_('File Name'), max_length=80)
    target = models.CharField(_('Target'), max_length=80, null=True)
    perm = models.IntegerField(_('Permisions'), null=True)
    owner = models.CharField(_('Owner'), max_length=55, null=True)
    group = models.CharField(_('Group'), max_length=55, null=True)

    def __unicode__(self):
        return self.filename

    class Admin:
        list_display = ('filename', 'target', 'owner', 'perm')

    class Meta:
        verbose_name = _('Additional File')
        verbose_name_plural = _('Additional Files')

class IntraFiles(models.Model): # Package
    filename = models.CharField(_('File Name'), max_length=150)
    path = models.CharField(_('Path'), max_length=300)
    type = models.CharField(_('Type'), max_length=80)
    size = models.IntegerField(_('Size'))
    mode = models.IntegerField(_('Mode'))
    hash = models.CharField(_('Hash'), max_length=80)
    
    def __unicode__(self):
        return self.filename
    
    class Admin:
        list_display = ('filename', 'type', 'path')
        fields = (('Genel', {'fields': ('filename', 'type', 'path','size', 'hash', 'mode')}),)

    class Meta:
        verbose_name = _("IntraFile")
        verbose_name_plural = _("IntraFiles")
class Email(models.Model):
    email = models.EmailField(_('Email'))
    
    def __str__(self):
        return self.email
    
    class Admin:
        pass

class Packager(models.Model):
    name = models.CharField(_('Name'), max_length=80)
    email = models.ManyToManyField(Email, verbose_name=_('Email'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Packager')
        verbose_name_plural = _('Packagers')
    
    class Admin:
        list_display = ('name',)

class Update(models.Model): # Source 
    release = models.IntegerField(_('Release'))
    type = models.CharField(_('Type'), max_length=50, null=True)
    date = models.DateField(_('Date'))
    version = models.CharField(_('Version'), max_length=50)
    comment = models.CharField(_('Comment'), max_length=3000)
    packager = models.ForeignKey(Packager, verbose_name=_('Packager'))
    email = models.ManyToManyField(Email, verbose_name=_('Email'))
    
    # Eski paketçi modeli
    #name = models.CharField(_('Name'), max_length=80)
    #email = models.EmailField(_('Email'))

    def __unicode__(self):
        return str(self.release) + "-" + self.version + "-" + self.comment
    
    class Admin:
        list_display = ('release', 'date', 'version', 'packager')

    class Meta:
        verbose_name = _("Update")
        verbose_name_plural = _("Updates")
        get_latest_by = 'date'
        
class Source(models.Model):
    # Repo & Component
    repo = models.ForeignKey(Repo, verbose_name=_('Repository'))
    component = models.ForeignKey(Component, verbose_name=_('Component'))

    # Kaynak bilgileri
    name = models.CharField(_('Name'), max_length=80)
    homepage = models.URLField(_('Homepage'))
    version = models.CharField(_('Version'), max_length=40)

    # Paket bilgileri ForeignKey oluyor. 2 Ocak'08 - 17:48 (İstanbul-Bursa Otobüsü) ;P
    packager = models.ForeignKey(Packager, verbose_name=_('Packager'))
    #packager = models.CharField(_('Packager'), max_length=80)
    #email = models.EmailField(_('Email'))

    license = models.ManyToManyField(License, verbose_name=_("License"))
    isa = models.ManyToManyField(IsA, verbose_name=_('Is A'))
    summary = models.ManyToManyField(Summary, verbose_name=_('Summary'))
    desc = models.ManyToManyField(Description, verbose_name=_('Description'), blank=True, null=True)
    archive_name = models.CharField(_('Name'), max_length=80)
    archive_sha1sum = models.CharField(_('Sha1Sum'), max_length=80)
    archive_type = models.CharField(_('Type'), max_length=10)
    archive_url = models.CharField(_('URL'), max_length=250)
    build_dep = models.ManyToManyField(Dependency, verbose_name=_('Build Dependencies'), related_name='build_dep', null=True, blank=True)
    patch = models.ManyToManyField(Patch, verbose_name=_('Patches'), null=True, blank=True)
    update = models.ManyToManyField(Update, verbose_name=_('Update'))
    packages = models.ManyToManyField("Package", verbose_name=_('Packages'), related_name="packages", null=True, blank=True)
    
    ### Slug ###
    slug = models.SlugField(_('Source Slug'), prepopulate_from=("name",))

    ### İstatistik ###
    last_update = models.DateField(_('Last Update'), blank=True)

templates/pak/package.html
{% extends "base.html" %}

{% load library %}

{% block extratitle %}Package: {{ package.name }} | {% endblock %}

{% block content %}
<div id="Source">

<strong>Beni Sil: Source şablonundan kopya + source >>> package.source<br /><br /></strong>

Repository: {{package.source.repo.name}}<br />
Component: {{package.source.component.component}} <br />

Name: {{ package.source.name }} <br />
Homepage: {{ package.source.homepage }}<br />
Version: {{ package.source.version }} <br />
Packager: {{ package.source.packager }}<br />
Email: {{ package.source.email }} <br />
License: {{ package.source.license }} <br />
IsA: {{ package.source.isa }} <br />
{% for sum in package.source.summary.all %}
    Summary: {{ sum.lang }} - {{ sum.summary }} <br />
{% endfor %}

{% for desc in package.source.desc.all %}
    Description: {{ desc.lang }} - {{ desc.desc }} <br />
{% endfor %}

<br />
 
Archive: {{package.source.archive_name }} <br />
Sha1Sum: {{package.source.archive_sha1sum }}<br />
Type: {{package.source.archive_type }} <br />
URI: {{package.source.archive_url }} <br />

<br />
BuildDependencies<br />
{% for dep in package.source.build_dep.all %}
    {{ dep.name }}
    {% if dep.versionFrom %}
       VersiomFrom: {{ dep.versionFrom }}
    {% endif %}
    {% if dep.versionTo %}
       VersionTo: {{ dep.versionTo }}
    {% endif %}
    {% if dep.version %}
       Verion: {{ dep.version }}
    {% endif %}
    {% if dep.releaseFrom %}
        ReleaseFrom: {{ dep.releaseFrom }}
    {% endif %}
    {% if dep.releaseTo %}
        ReleaseTo: {{ dep.releaseTo }}
    {% endif %}
    {% if dep.release %}
        Release: {{ dep.release }}
    {% endif %}
    <br />
{% endfor %}

<br />

Patches:<br />
{% for patch in package.source.patch.all %}
    {{ patch.name }}
    {% if patch.level %}
        Level: {{ patch.level }}
    {% endif %}
    <br />
{% endfor %}

<br />

Packages: 
{% for package in package.source.packages.all %}
    {{ package.name }}<br />
         RuntimeDependencies: <br />
         {% for dep in package.runtime_dep.all %}
             Dep: {{ dep.name }}
             {% if dep.versionFrom %}
                VersiomFrom: {{ dep.versionFrom }}
             {% endif %}
             {% if dep.versionTo %}
                VersionTo: {{ dep.versionTo }}
             {% endif %}
             {% if dep.version %}}
                Verion: {{ dep.version }}
             {% endif %}
             {% if dep.releaseFrom %}
                 ReleaseFrom: {{ dep.releaseFrom }}
             {% endif %}
             {% if dep.releaseTo %}
                 ReleaseTo: {{ dep.releaseTo }}
             {% endif %}
             {% if dep.release %}
                 Release: {{ dep.release }}
             {% endif %}
             <br />
        {% endfor %}            
        <br />
        Files: <br />
        {% for file in package.files.all %}
             Type: {{ file.fileType }} Path: {{ file.path }}
             <br />
        {% endfor %}

        <br />
        AdditionalFiles: <br />
        {% for a_file in package.a_files.all %}
           {{ a_file.filename }}
           {% if file.target %}
               {{ a_file.target }}
           {% endif %}
           {% if a_file.perm %}
               {{ a_file.perm }}
           {% endif %}
           {% if a_file.owner %}
               {{ a_file.owner }}
           {% endif %}
           {% if a_file.group %}
               {{ a_file.group }}
           {% endif %}
           <br />
        {% endfor %}
{% endfor %}

<br />

Update: <br />
{% for update in package.source.update.all %}
    {{ update.release }}
    {% if update.type %}
        {{ update.type }}
    {% endif %}
    {{ update.date|date:"j F, Y" }}
    {{ update.version }}
    {{ update.name }}
    {{ update.email }}
    <br />
{% endfor %}

<br />

Last Update: {{package.source.last_update|date:"j F, Y" }} <br />
First Release: {{package.source.firstReleaseDate|date:"j F, Y" }} <br />
Build Script Size: {{package.source.buildScriptSize }} <br />
Spec Script Size: {{package.source.specScriptSize }} <br />
Update Count: {{package.source.updateCount }} <br />
Patch Count: {{package.source.patchCount }} <br />

</div>
{% endblock%}

{% block secondary_content %}
Secondary Content
{% endblock %}

templates/pak/packager.html
{% extends "base.html" %}

{% load i18n %}

{% load library %}

{% block content %}

{% trans "Packager" %}: {{ packager.name }}
<ul>
    <li> {% trans "Emails" %}: 
        <ul>
        {% for email in packager.email.all %}
        <li>{{ email }}</li>
        {% endfor %}
        </ul>
    </li>
    <li>{% trans "Sources" %}: <a href="/pisi/packager/{{ packager.name }}/sources">{{ packager.source_set.count }}</a>
        <ul>
            <li>{% trans "Last 5 sources" %};
                <ul>
                {% for update in last_sources %}
                    <li><a href="/pisi/source/{{ update.source_set.all.0.id }}">{{ update.source_set.all.0.name }}</a> -- {{ update.date|date:"j F, Y" }}</li>
                {% endfor %}
                </ul>
            </li>
        </ul>
    </li>
    <li>{% trans "Updates" %}: <a href="/pisi/packager/{{ packager.name }}/updates">{{ packager.update_set.count }}</a>
        <ul>
            <li>{% trans "Last 5 updates" %};
                <ul>
                {% for update in last_updates %}
                <li><a href="/pisi/update/{{ update.id }}">{{ update.date|date:"j F, Y" }}</a> -- <a href="/pisi/source/{{ update.source_set.all.0.id }}">{{ update.source_set.all.0.name }}</a></li>
                {% endfor %}
                </ul>
            </li>
        </ul>
    </li>
</ul>
{% endblock%}

templates/pak/packager_sources.html
{% extends "pak/sources.html" %}
{% block caption %} {{ sources_list.0.packager }} - {% endblock %}

templates/pak/packager_updates.html
{% extends "pak/updates.html" %}
{% block caption %} {{ updates_list.0.packager }} - {% endblock %}

templates/pak/packagers.html
{% extends "base.html" %}

{% load i18n %}

{% load library %}

{% block content %}

<div id="sources">
<table>
	<caption>
	{% trans "Packagers" %}
	{% if is_paginated %}
	<span class="search-results">{% blocktrans %}Showing {{ results_per_page }} results per page of about {{ hits }} results in {{pages}} pages{% endblocktrans %}</span>
	{% endif %}
	</caption>
	<thead>
	  <tr>
	    <th>#</th>
	    <th>{% trans "Name" %}</th>
	    <th>{% trans "Packages" %}</th>
	    <th>{% trans "Updates" %}</th>
	    <th>{% trans "Email" %}</th>
	  </tr>
	</thead>	
	<tfoot>
	  <tr>
	    <th>#</th>
	    <th>{% trans "Name" %}</th>
	    <th>{% trans "Packages" %}</th>
	    <th>{% trans "Updates" %}</th>
	    <th>{% trans "Email" %}</th>
	  </tr>
	</tfoot>
	<tbody>
	{% for packager in packagers_list %}
	  <tr class="{% cycle 'rowA' 'rowB' %}">
	    <td>{{ packager.id }}</td>
	    <td><a href="/pisi/packager/{{ packager.name }}">{{ packager.name }}</a></td>
	    <td>{{ packager.source_set.count }}</td>
	    <td>{{ packager.update_set.count }}</td>
	    <td>
	    {% for email in packager.email.all %}
	    {{ email.email }},<br/>
	    {% endfor %}
	    </td>
	    </tr>
	{% endfor %}
	</tbody>
</table>
</div>

{% endblock%}

templates/pak/packages.html
{% extends "base.html" %}

{% load i18n %}

{% block extratitle %}{% trans "Package List" %} | {% endblock %}

{% block content %}
<div id="packages">
<table>
	<caption>
	{% trans "Package List" %}
	{% if is_paginated %}
	<span class="search-results">{% blocktrans %}Showing {{ results_per_page }} results per page of about {{ hits }} results in {{pages}} pages{% endblocktrans %}</span>
	{% endif %}
	</caption>
	<thead>
	  <tr>
	    <th></td>
	    <th>{% trans "Name" %}<span class="orderbuttons"><a href="./name">+</a> <a href="./-name">-</a></span></td>
	    <th>{% trans "Packager" %}</td>
	    <th>{% trans "Repository" %}</td>
	    <th>{% trans "Component" %}</td>
	    <th>{% trans "Version" %}</th>
	    <th>{% trans "Release" %}</th>
	    <th>{% trans "Last Update" %}</th>
	  </tr>
	</thead>	
	<tfoot>
	  <tr>
	    <th></td>
	    <th>{% trans "Name" %}</td>
	    <th>{% trans "Packager" %}</td>
	    <th>{% trans "Repository" %}</td>
	    <th>{% trans "Component" %}</td>
	    <th>{% trans "Version" %}</th>
	    <th>{% trans "Release" %}</th>
	    <th>{% trans "Last Update" %}</th>
	  </tr>
	</tfoot>
	<tbody>
	  {% for package in packages_list %}  
	  <tr class="{% cycle 'rowA' 'rowB' %}">
	    <td><a href="{{ package.source.homepage }}"><img src="/media/img/homepage_small_15.png"></a></td>
	    <td><a href="/pisi/package/{{ package.id }}">{{ package.name }}</a></td>
	    <td><a href="/pisi/packager/{{ package.source.packager }}">{{ package.source.packager }}</a></td>
	    <td><a href="/pisi/repository/{{ package.source.repo.name }}/packages">{{ package.source.repo.name }}</a></td>
	    <td><a href="#">{{ package.source.component.component }}</a></td>
	    <td>{{ package.source.version }}</td>
	    <td>{{ package.source.update.latest.release }}</td>
	    <td>{{ package.source.update.latest.date|date:"j F, Y" }}</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
</div>
{% endblock%}

templates/pak/repositories.html
{% extends "base.html" %}

{% load library %}

templates/pak/update.html
{% extends "base.html" %}

{% load i18n %}

{% block extratitle %}{% trans "Update" %}: {{ update.id }} - {{ update.date|date:"j F, Y" }} | {% endblock %}

{% block content %}
<div id="update">
    <span class="date">
        {% trans "Date" %}: {{ update.date|date:"j F, Y" }} <br />
    </span>
    <span class="release">
        {% trans "Release" %}: {{ update.release }} <br />
    </span>
    <span class="version">
        {% trans "Version" %}: {{ update.version }} <br />
    </span>
    <span class="type">
        {% trans "Type" %}: {{ update.type }} <br />
    </span>
    <span class="name">
        {% trans "Name" %}: {{ update.name }} <br />
    </span>
    <span class="email">
        {% trans "Email" %}: {{ update.email }} <br />
    </span>
    <span class="comment">
        {% trans "Comment" %}: {{ update.comment }} <br />
    </span>
    <span class="source_name">
        {% trans "Package" %}: {{ update.source_set.all.0.name }} <br />
    </span>
</div>
{% endblock %}

templates/pak/updates.html
{% extends "base.html" %}

{% load i18n %}

{% block extratitle %}{% trans "Update List" %} | {% endblock %}

{% block content %}
<div id="updates">
<table>
	<caption>
	{% block caption %} {% endblock %}
	{% trans "Update List" %} 
	{% if is_paginated %}
	<span class="search-results">{% blocktrans %}Showing {{ results_per_page }} results per page of about {{ hits }} results in {{pages}} pages{% endblocktrans %}</span>
	{% endif %}
	</caption>
	<thead>
	  <tr>
	    <th>{% trans "Date" %}<span class="orderbuttons"><a href="./date">+</a> <a href="./-date">-</a></span></td>
	    <th>{% trans "Package" %}</td>
	    <th>{% trans "Updater" %}<span class="orderbuttons"><a href="./name">+</a> <a href="./-name">-</a></span></td>
	    <th>{% trans "Repository" %}</td>
	    <th>{% trans "Type" %}<span class="orderbuttons"><a href="./type">+</a> <a href="./-type">-</a></span></td>
	    <th>{% trans "Version" %}<span class="orderbuttons"><a href="./version">+</a> <a href="./-version">-</a></span></th>
	    <th>{% trans "Release" %}<span class="orderbuttons"><a href="./release">+</a> <a href="./-release">-</a></span></th>
	  </tr>
	</thead>	
	<tfoot>
	  <tr>
	    <th>{% trans "Date" %}</td>
	    <th>{% trans "Package" %}</td>
	    <th>{% trans "Updater" %}</td>
	    <th>{% trans "Repository" %}</td>
	    <th>{% trans "Type" %}</td>
	    <th>{% trans "Version" %}</th>
	    <th>{% trans "Release" %}</th>
	  </tr>
	</tfoot>
	<tbody>
	  {% for update in updates_list %}  
	  <tr class="{% cycle 'rowA' 'rowB' %}">
	    <td><a href="/pisi/update/{{ update.id }}">{{ update.date|date:"j F, Y" }}</a></td>
	    <td><a href="/pisi/source/{{ update.source_set.all.0.id }}">{{ update.source_set.all.0.name }}</td>
	    <td><a href="/pisi/packager/{{ update.packager }}">{{ update.packager }}</a></td>
	    <td><a href="/pisi/repository/{{ update.source_set.all.0.repo.name }}/sources">{{ update.source_set.all.0.repo.name }}</td>
	    <td>
	    <center>	    
	    {% if update.type %}<a href="/pisi/updates/type/{{ update.type }}">{% endif %}
	    {{ update.type|default_if_none:"-" }}</td>
	    {% if update.type %}</a>{% endif %}
	    </center>
	    <td 
	    {% if update.source_set.all.0.update.all.1.version %}
	    title="{% trans "Previous Version" %}: {{ update.source_set.all.0.update.all.1.version }}"
	    {% else %}title="{% trans "First release" %}"
	    {% endif %}
	    ><span>{{ update.version }}</span></td>
	    <td>{{ update.release }}</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
</div>
{% endblock%}